### ISSUE TITLE
can not find the repository

### ISSUE THREAD

**Issue by arthurlintw** [ebiken/doc-network#1]
Hi, Ebiken:
World you mind to tell me where can I get the script files ?
Thanks .

 git clone https://github.com/pontonetworks/demoapi.git
git clone https://github.com/pontonetworks/ponto-xp.git
~/3.1/ponto-xp$ sudo ./netDemo01-run.sh
~/3.1/ponto-xp$ sudo ./xpOvsSandBox.sh start

**Comment by ebiken** [comment]
Hi. It looks like you have accessed `test.md` which is a hidden page I just forgot to remove after testing wiki formats. The repo and the script you've mentioned is private so cannot give you access to.
I have removed `test.md` from the wiki. Sorry for the confusion.
